---
# Service permetant de faire la redirection vers le pod de front (tout ce qui viens de l'extérieur)
kind: Service
apiVersion: v1
metadata:
  # Nom du service
  name: front-svc
spec:
  selector:
    #  Label du pod de redirection (nom présent dans le descriptor.yml)
    app: k8s-tp
    name: front
  ports:
  - protocol: TCP
    # Port d'entré (tout ce qui arrive de n'importe quel pod)
    port: 80
    # Port de redirection, uniquement destiné au pod indiqué via le selecteur
    targetPort: 80