---
# Service permétant de faire la redirection vers le pod mysql
kind: Service
apiVersion: v1
metadata:
  # Nom du service
  name: mysql-svc
spec:
  selector:
    #  Label du pod de redirection (nom présent dans le descriptor.yml)
    app: k8s-tp
    name: database
  ports:
  - protocol: TCP
    # Port d'entré (tout ce qui arrive de n'importe quel pod)
    port: 3306
    # Port de redirection, uniquement destiné au pod indiqué via le selecteur
    targetPort: 3306